In [1]:
import torch


In [2]:
print(torch.__version__)

2.5.1+cu121


In [3]:
if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available
Tesla T4


# **CREATING TENSOR**

In [4]:
a=torch.empty(2,3)

In [5]:
a

tensor([[2.1715e-18, 6.9064e-07, 3.2876e+21],
        [6.6015e-07, 6.5548e-10, 7.9963e+20]])

In [6]:
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

THE BELOW 2 PROVIDES DIFFERT RANDOM VALUES

In [11]:
torch.rand(2,3)

tensor([[0.0271, 0.6084, 0.3394],
        [0.2249, 0.4847, 0.6676]])

In [12]:
torch.rand(2,3)

tensor([[0.4663, 0.4201, 0.4558],
        [0.2603, 0.5501, 0.3126]])

GETTING SAME RANDOM VALUES INSIDE TENSOR

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

THE ABOVE ARE PROVIDING THE SAME VALUES

# **USING TENSORS**

In [15]:
torch.tensor([[1,2,3],[4,5,6]])  #DESIRED ELEMENTS ARE IN THE INPUT

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
#OTHER WAYS TO GENERATE A TENSOR IN TORCH
torch.arange(0,10,2)


tensor([0, 2, 4, 6, 8])

In [22]:
torch.arange(0,50,3)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [24]:
torch.linspace(0,10,6)  #6 EVENLY SPREAD VALUES  //  WITH THE RANGE 0 TO 10

tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [25]:
torch.eye(5)  # creates the identity matrix or 5 rows

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
torch.full((3,3),5)   # 3X3 MATRIX WITH EVERY ELEMENT AS 5 HERE

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# **TENSOR SHAPES**

In [30]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(a)
a.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

CREATING TENSOR OF ALREADY GIVEN SHAPES

In [35]:
torch.empty_like(a)

tensor([[ 97179538928096, 137706320838576,               0],
        [              0,               0,               0]])

In [32]:
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [36]:
torch.ones_like(a)  #PROVIDES THE SHAPE OF "A" TO THE ONES MATRIX

tensor([[1, 1, 1],
        [1, 1, 1]])

In [38]:
torch.rand_like(a)  #PROVIDES error!!!  BECAUSE THE rand_like() function is being
                    #operated with float data type // but here datatype is
                    #in integer form

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [39]:
torch.rand_like(a,dtype=torch.float)  #PROVIDES THE SHAPE OF "A" TO THE ONES MATRIX

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# TENSOR DATATYPE

In [40]:
a.dtype

torch.int64

In [42]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [43]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [45]:
a.dtype

torch.int64

In [49]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [50]:
a.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# MATHEMATICAL OPERATIONS ON TENSORS

SCALAR OPERATIONS

In [51]:
a+3


tensor([[4, 5, 6],
        [7, 8, 9]])

In [54]:
a*=10

In [55]:
a

tensor([[100, 200, 300],
        [400, 500, 600]])

In [56]:
a-10

tensor([[ 90, 190, 290],
        [390, 490, 590]])

In [57]:
a

tensor([[100, 200, 300],
        [400, 500, 600]])

In [58]:
a/2

tensor([[ 50., 100., 150.],
        [200., 250., 300.]])

In [60]:
a//2#INTEGER DIVISION

tensor([[ 50, 100, 150],
        [200, 250, 300]])

In [62]:
(a+3)%2

tensor([[1, 1, 1],
        [1, 1, 1]])

In [63]:
a**2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

ELEMENT WISE OPERATIONS

In [78]:
a=torch.randint(size=(2,3),low=0,high=10)
b=torch.rand(2,3)



In [79]:
a

tensor([[7, 7, 8],
        [3, 6, 1]])

In [80]:
b

tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590]])

In [81]:
a+b

tensor([[7.3039, 7.6726, 8.5740],
        [3.9233, 6.9178, 1.7590]])

In [82]:
a-b

tensor([[6.6961, 6.3274, 7.4260],
        [2.0767, 5.0822, 0.2410]])

In [83]:
a*b

tensor([[2.1273, 4.7084, 4.5917],
        [2.7699, 5.5068, 0.7590]])

In [84]:
a/b

tensor([[23.0335, 10.4070, 13.9382],
        [ 3.2492,  6.5373,  1.3175]])

In [85]:
a**b

tensor([[1.8065, 3.7020, 3.2987],
        [2.7575, 5.1784, 1.0000]])

In [86]:
a%b

tensor([[0.0102, 0.2738, 0.5385],
        [0.2301, 0.4932, 0.2410]])

In [87]:
c=torch.tensor([1,-2,+3,-6])

In [88]:
torch.abs(c)   #PROVIDES THE ABSOLUTE VALUE

tensor([1, 2, 3, 6])

In [89]:
torch.neg(c)

tensor([-1,  2, -3,  6])

In [98]:
d=torch.rand(2,3)
d

tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [100]:
torch.round(d)

tensor([[0., 1., 0.],
        [0., 1., 0.]])

In [102]:
torch.ceil(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [104]:
torch.floor(d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [105]:
torch.trunc(d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [107]:
torch.clamp(d,min=.4,max=.6)  # SUBSTITUTES THE VALUE WITH .4 WHEN THE VALUE IS LESSER THE .4
                              #SUBSTITUTE THE VALUE WITH .6 WHEN THE VALUE IS MORE THEN .6
                              # VALUE BTW .4  -  .6 WILL REMAIN THE SAME

tensor([[0.4000, 0.6000, 0.4000],
        [0.4000, 0.6000, 0.4234]])

REDUCTION OPERATION

In [109]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float)


In [110]:
e

tensor([[3., 1., 0.],
        [2., 1., 2.]])

In [111]:
torch.sum(e)

tensor(9.)

In [113]:
torch.sum(e,dim=0)  #SUM ALONG COLUMN

tensor([5., 2., 2.])

In [114]:
torch.sum(e,dim=1)  #SUM ALONG ROW

tensor([4., 5.])

In [115]:
torch.mean(e)

tensor(1.5000)

In [116]:
torch.mean(e,dim=0)

tensor([2.5000, 1.0000, 1.0000])

In [117]:
torch.mean(e,dim=1)

tensor([1.3333, 1.6667])

In [118]:
torch.median(e)

tensor(1.)

In [119]:
torch.median(e,dim=0)

torch.return_types.median(
values=tensor([2., 1., 0.]),
indices=tensor([1, 0, 0]))

In [120]:
torch.median(e,dim=1)

torch.return_types.median(
values=tensor([1., 2.]),
indices=tensor([1, 0]))

In [121]:
torch.std(e)   #STANDARD DEVIATION

tensor(1.0488)

In [122]:
torch.min(e)

tensor(0.)

In [123]:
torch.max(e)

tensor(3.)

In [124]:
torch.prod(e)  #  PRODUCT OF EVERY ELEMENT OF THE MATRIX

tensor(0.)

In [125]:
torch.var(e)  # varience

tensor(1.1000)

In [126]:
torch.argmin(e)  #PROVIDES THE LOCATAION OF THE MINIMUN ELEMENT

tensor(2)

In [128]:
torch.argmax(e)   # PROVIDES THE LOCATION OF THE MAXIMUM ELEMENT

tensor(0)

In [129]:
e

tensor([[3., 1., 0.],
        [2., 1., 2.]])

# **MATRIX OPERATIONS**

In [130]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

MATRIX MULTIPLICATION

In [132]:
f

tensor([[7, 9, 2],
        [4, 6, 6]])

In [133]:
g

tensor([[8, 4],
        [9, 0],
        [7, 9]])

In [135]:
torch.matmul(f,g)  #MATRIX MULTIPLICATION

tensor([[151,  46],
        [128,  70]])

In [141]:
#DOT PRODUCT
vec1=torch.tensor([1,2,3])
vec2=torch.tensor([4,5,6])

torch.dot(vec1,vec2)

tensor(32)

In [144]:
f

tensor([[7, 9, 2],
        [4, 6, 6]])

In [147]:
#TRANSPOSE
torch.transpose(f,0,1)   #DIMENTIONS TO SWAP ARE 0,1

tensor([[7, 4],
        [9, 6],
        [2, 6]])

In [159]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float)
h

tensor([[2., 3., 7.],
        [0., 2., 5.],
        [2., 8., 0.]])

In [160]:
torch.inverse(h)  #WORKS ON SQUARE MATRIX WITH FLOATING VALUE

tensor([[ 0.5128, -0.7179, -0.0128],
        [-0.1282,  0.1795,  0.1282],
        [ 0.0513,  0.1282, -0.0513]])

In [161]:
torch.det(h)  #WORKS ON SQUARE MATRIX WITH FLOATING VALUE

tensor(-78.)

# **COMPARISION OPERATIONS**

In [162]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

In [163]:
i

tensor([[2, 5, 3],
        [6, 7, 8]])

In [164]:
j

tensor([[1, 2, 3],
        [2, 7, 9]])

In [165]:
j==i

tensor([[False, False,  True],
        [False,  True, False]])

In [166]:
j!=i

tensor([[ True,  True, False],
        [ True, False,  True]])

In [167]:
j>i

tensor([[False, False, False],
        [False, False,  True]])

In [168]:
j<i

tensor([[ True,  True, False],
        [ True, False, False]])

In [169]:
j<=i

tensor([[ True,  True,  True],
        [ True,  True, False]])

In [170]:
j>=i

tensor([[False, False,  True],
        [False,  True,  True]])

# **SPECIAL FUNCTIONS**

In [171]:
k=torch.randint(size=(2,3),low=0,high=10)

In [172]:
k

tensor([[3, 9, 7],
        [7, 5, 9]])

In [173]:
torch.log(k)

tensor([[1.0986, 2.1972, 1.9459],
        [1.9459, 1.6094, 2.1972]])

In [174]:
torch.exp(k)

tensor([[  20.0855, 8103.0840, 1096.6332],
        [1096.6332,  148.4132, 8103.0840]])

In [175]:
torch.sqrt(k)

tensor([[1.7321, 3.0000, 2.6458],
        [2.6458, 2.2361, 3.0000]])

In [176]:
torch.sigmoid(k)

tensor([[0.9526, 0.9999, 0.9991],
        [0.9991, 0.9933, 0.9999]])

In [179]:
torch.softmax(h,dim=0)  #REQUIRES FLOATING VALUES

tensor([[4.6831e-01, 6.6764e-03, 8.8009e-01],
        [6.3379e-02, 2.4561e-03, 1.1911e-01],
        [4.6831e-01, 9.9087e-01, 8.0254e-04]])

In [180]:
torch.relu(k)

tensor([[3, 9, 7],
        [7, 5, 9]])

#**INPLACE OPERATIONS**

In [191]:
m=torch.randint(size=(2,3),low=0,high=10)
n=torch.randint(size=(2,3),low=0,high=10)

In [192]:
m  #(-) UNDERSCORE CONVERTS INTO INPLACE OPERATIONS

tensor([[5, 8, 0],
        [8, 9, 6]])

In [193]:
n

tensor([[1, 9, 6],
        [8, 1, 7]])

In [194]:
m+n  # CREATES NEW TENSOR & IF IT IS A BIG DATASET THEN IT REQUIRES ALOT OF TIME & SPACE

tensor([[ 6, 17,  6],
        [16, 10, 13]])

In [195]:
m

tensor([[5, 8, 0],
        [8, 9, 6]])

In [196]:
n

tensor([[1, 9, 6],
        [8, 1, 7]])

In [197]:
m.add_(n)  #CHANGES THE ORIGINAL TENSOR

tensor([[ 6, 17,  6],
        [16, 10, 13]])

In [199]:
m

tensor([[ 6, 17,  6],
        [16, 10, 13]])

In [200]:
n

tensor([[1, 9, 6],
        [8, 1, 7]])

#**COPYING A TENSOR**

In [215]:
a=torch.rand(2,3)

In [216]:
a


tensor([[0.2440, 0.8994, 0.1041],
        [0.9193, 0.6201, 0.3658]])

In [217]:
id(a)

137706323794000

In [218]:
b=a
b

tensor([[0.2440, 0.8994, 0.1041],
        [0.9193, 0.6201, 0.3658]])

In [219]:
a[0][0]=0

In [220]:
a

tensor([[0.0000, 0.8994, 0.1041],
        [0.9193, 0.6201, 0.3658]])

In [221]:
b

tensor([[0.0000, 0.8994, 0.1041],
        [0.9193, 0.6201, 0.3658]])

In [222]:
id(a)

137706323794000

In [223]:
id(b)

137706323794000

a,b dono mein chnge ho gaya a[0][0] =0 se

In [224]:
b=a.clone()

In [225]:
b

tensor([[0.0000, 0.8994, 0.1041],
        [0.9193, 0.6201, 0.3658]])

In [226]:
a

tensor([[0.0000, 0.8994, 0.1041],
        [0.9193, 0.6201, 0.3658]])

In [227]:
a[0][1]=2

In [228]:
a

tensor([[0.0000, 2.0000, 0.1041],
        [0.9193, 0.6201, 0.3658]])

In [229]:
id(a)

137706323794000

In [230]:
b

tensor([[0.0000, 0.8994, 0.1041],
        [0.9193, 0.6201, 0.3658]])

In [231]:
id(b)

137705833295568

#**RESHAPING TENSORS**

In [234]:
o=torch.ones(4,4)

In [237]:
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [235]:
o.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [238]:
o.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [239]:
b=torch.rand(2,3,4)

In [240]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [242]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

#UNSQUEEZE

In [244]:
#UNSQUEEZE
c=torch.rand(226,226,4)

In [245]:
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 4])

In [246]:
c.unsqueeze(dim=1).shape

torch.Size([226, 1, 226, 4])

In [247]:
c.unsqueeze(dim=2).shape

torch.Size([226, 226, 1, 4])

In [248]:
c.unsqueeze(dim=3).shape

torch.Size([226, 226, 4, 1])

SQUEEZE

In [249]:
d=torch.rand(1,20)


In [250]:
d.squeeze(dim=0).shape

torch.Size([20])

In [251]:
d.squeeze(dim=1).shape

torch.Size([1, 20])

#**TENSOR OPERTIONS ON GPU VS CPU**

In [252]:
torch.cuda.is_available()

True

In [253]:
device=torch.device('cuda')

In [254]:
torch.rand(2,3).to(device)

tensor([[0.5669, 0.1812, 0.5910],
        [0.1887, 0.0227, 0.7823]], device='cuda:0')

In [256]:
a=torch.rand(2,3)
a

tensor([[0.3155, 0.4057, 0.5754],
        [0.6716, 0.9085, 0.4883]])

In [257]:
b=a.to(device)   #shifted to GPU

In [259]:
b

tensor([[0.3155, 0.4057, 0.5754],
        [0.6716, 0.9085, 0.4883]], device='cuda:0')

In [264]:
import torch
import time
size=10000


matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

start_time=time.time()
result=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time() - start_time

print(f"cpu takes",cpu_time,"time for complete execution" )

matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')
start_time=time.time()
result=torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time=time.time() - start_time

print(f"gpu takes",gpu_time,"time for complete execution")

print("\nspeedup/ratio:",cpu_time/gpu_time)

cpu takes 16.371829509735107 time for complete execution
gpu takes 0.00037789344787597656 time for complete execution

speedup/ratio: 43323.93059936909
